src/Entity/Common/EntityId.php
<?php

declare(strict_types=1);

namespace App\Entity\Common;

interface EntityId
{
    public function getId(): ?int;
}

src/Controller/DefaultController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/', name: 'app')]
final class DefaultController extends AbstractController
{
    public function __invoke(): Response
    {
        return $this->redirectToRoute('app_index');
    }
}

templates/default/index.html.twig
{% extends 'layout.html.twig' %}

{% block pageTitle %}
    Dashboard
{% endblock %}

{% block pageActions %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-status-top bg-primary"></div>
                <div class="card-body">
                    <h3 class="card-title">Visits</h3>
                    <p>{{ countVisits }}</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-status-top bg-primary"></div>
                <div class="card-body">
                    <h3 class="card-title">Short URL's</h3>
                    <p>{{ countShortUrls }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            {{ form_start(form) }}
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Create a short URL</h4>
                </div>
                <div class="card-body">
                    {{ form_row(form.url) }}
                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{ path('app_short_url_add') }}" class="btn btn-link ms-auto">Advanced options</a>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Recently created URLs</h4>
                </div>
                <table class="table table-vcenter table-hover table-striped card-table">
                    <thead>
                    <tr>
                        <th>Created at</th>
                        <th>Short URL</th>
                        <th>Long URL / Title</th>
                        <th>Visits</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for shortUrl in recentlyCreatedShortUrls %}
                        {% set shortedUrl = url('app_redirect', { code: shortUrl.code }) %}
                        <tr>
                            <td>{{ shortUrl.created|date }}</td>
                            <td>
                                <a
                                   href="{{ shortedUrl }}"
                                   title="{{ shortedUrl }}"
                                   target="_blank"
                                >
                                    {{ shortedUrl }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ shortUrl.url }}" title="{{ shortUrl.url }}" target="_blank">
                                    {% if shortUrl.title is not null %}
                                        {{ shortUrl.title }}
                                    {% else %}
                                        {{ shortUrl.url|u.truncate(100, '...') }}
                                    {% endif %}
                                </a>
                            </td>
                            <td>{{ shortUrl.visits|length }}</td>
                            <td class="text-end">
                                <div class="btn-group">
                                    <span
                                            class="copy-to-clipboard btn btn-sm btn-secondary"
                                            title="Copy short URL to clipboard"
                                            data-bs-toggle="tooltip"
                                            data-clipboard-text="{{ shortedUrl }}"
                                    >
                                        <span class="iconify" data-icon="fa6-solid:clipboard"></span>
                                    </span>
                                    <a href="{{ path('app_short_url_edit', { shortUrl: shortUrl.id }) }}" data-bs-toggle="tooltip" title="Edit" class="btn btn-sm btn-primary">
                                        <span class="iconify" data-icon="fa6-solid:pencil"></span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}